### ISSUE TITLE
Redirect Handling

### ISSUE THREAD

**Issue by sandoramix** [Sandoramix/42-minishell#25]
# Implementare il handling dei redirect

## Descrizione:

Data la lista di blocchi di commando (t_list * -> val) -> (t_command *)
Si devono:

- Scorrere quelli che sono i redirect di input `(t_command * -> in_redirects)`:
  - `<` + nome file dopo
  - Il heredoc `<<` (con la propria implementazione)
- Scorrere quelli che sono i redirect di output (`>` e `>>`) `(t_command * -> out_redirects)`

L'ordine delle operazioni dovrebbe essere il seguente:

1. Si scorre i redirect di input creando solamente gli heredoc. Se il nodo del heredoc + il delimitatore non sono alla fine, cioe' non e' l'ultimo redirect, si va a eliminare il file di quel heredoc.
2. Si scorre di nuovo i redirect di input considerando solo i `<` , dove al primo file invalido si va a stampare il messaggio di errore "<file>: No such file or directory" (o roba simile), e settare il redirect di input a `NULL`, cioe' non ci sono file da leggere in input.
  2.1 Se invece va tutto bene, e l'ultimo nodo e' quello del `<` si va a settare il nome di file di input. 
4. Si scorre la lista dei redirect di output aprendoli nella modalita' giusta
  4.1 Per `>` si apre il file in modalita' `O_CREAT | O_TRUNC | O_WRONLY`
  4.2 Per `>>` si apre il file in modalita `O_CREAT | O_APPEND | O_WRONLY`

**Comment by Martybb01** [comment]
per < se il file non esiste bisogna ritornare errore e NON crearlo. Se invece esiste va aperto in modalita R_ONLY.
